[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kernel"
test = false
bench = false

[dependencies]
bootloader_api = "0.11.0"
log = { version = "0.4.17", default-features = false }
conquer-once = { version = "0.4.0", default-features = false }
font8x8 = { version = "0.3.1", default-features =false, features= ["unicode"] }
spinning_top = "0.3.0"
x86_64 = "0.15.4"
pic8259 = "0.11.0"
pc-keyboard = "0.8.0"
linked_list_allocator = "0.10.5"
crossbeam-queue = { version = "0.3.8", default-features = false, features = ["alloc"] }
futures-util = { version = "0.3.28", default-features = false, features = ["alloc"] }